### ISSUE TITLE
Replace the annotation-based with prefix-based tests

### ISSUE THREAD

**Issue by peter279k** [DeGraciaMathieu/Riddler#5]
According to the PHPUnit [doc](https://phpunit.readthedocs.io/en/7.1/writing-tests-for-phpunit.html), the ```test``` method has two approaches to tag the tests.
The one is ```prefix``` and another one is ```annotation```.
Which one is you prefer? It seems that you use the annotation to do this.

I think we use prefix-based is better than using annotation because I think it's readable.
If you prefer the annotation approach, we can close this issue.

Thanks.

**Comment by DeGraciaMathieu** [comment]
Hello,
I have no preference... but I think rewrite the tests soon.
The Test.php is really too bloated !
Thanks !
